services:
  kit:
    image: "rtdt-kit-app:latest"
    restart: unless-stopped
    build:
      context: .
      dockerfile: kit-app/Dockerfile
      network: host
    depends_on:
      aeronim:
        condition: service_started
    privileged: true
    ports:
     - "1024:1024/udp"
     - "49100:49100/tcp"
     - "47995-48012:47995-48012/tcp"
     - "49000-49007:49000-49007/tcp"
     - "47995-48012:47995-48012/udp"
     - "49000-49007:49000-49007/udp"
    environment:
      CUDA_VISIBLE_DEVICES: "${CUDA_DEVICE_KIT:-0}"
      OMNI_USER: "$OMNI_USER"
      OMNI_PASS: "$OMNI_PASS"
      KIT_APP: "${KIT_APP:-omni.rtwt.webrtc.kit}"
      USD_URL: "${USD_URL:-/home/ubuntu/usd/world_rtwt_minimal.usda}"
      STL_PATH_FORMAT: "${STL_PATH_FORMAT:-/data/low_res/detailed_car_{}/aero_suv_low.stl}"
      NIM_TRITON_IP_ADDRESS: "${NIM_TRITON_IP_ADDRESS:-aeronim}"
      NIM_TRITON_HTTP_PORT: "${NIM_TRITON_HTTP_PORT:-8080}"
      SenderTimeout: "${STREAMSDK_SENDER_TIMEOUT:-100000}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    volumes:
      - "ov-cache:/home/ubuntu/.cache/ov"
      - "ov-local-share:/home/ubuntu/.local/share/ov/"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rtwt

  web:
    image: "rtdt-web-app:latest"
    restart: unless-stopped
    build:
      context: web-app
      network: host
    ports:
      - "${WEB_HOST_PORT:-5273}:80/tcp"
    networks:
      - rtwt
    depends_on:
      kit:
        condition: service_started

  aeronim:
    image: "nvcr.io/nim/nvidia/domino-automotive-aero:2.0.0"
    runtime: nvidia
    environment:
      CUDA_VISIBLE_DEVICES: "${CUDA_DEVICE_AERONIM:-1}"
      NGC_API_KEY: "${NGC_API_KEY}"
    ipc: host
    ports:
      - "8080:8080"
    networks:
      - rtwt
volumes:
  ov-cache:
  ov-local-share:

networks:
  rtwt:
    driver: bridge