# Default values for rtdt-chart
global:
  storageClass: "microk8s-hostpath"
kit:
  image:
    repository: rtdt-kit-app
    tag: latest
    pullPolicy: IfNotPresent
  environment:
    KIT_APP: "omni.rtwt.app.webrtc.kit"
    USD_URL: "/home/ubuntu/usd/world_rtwt_Main_v1.usda"
    ZMQ_IP: "127.0.0.1"
    ZMQ_FIRST_PORT: "5555"
    ZMQ_REQUEST_TIMEOUT: "5000"
    ZMQ_REQUEST_QUEUE_SIZE: "1"
    STREAMSDK_SENDER_TIMEOUT: "100000"
    SenderTimeout: "100000"
  gpu:
    deviceId: "0"

web:
  image:
    repository: rtdt-web-app
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
    targetPort: 5273

aeronim:
  image:
    repository: nvcr.io/nim/nvidia/domino-automotive-aero
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  environment:
    NGC_API_KEY: "${NGC_API_KEY}"
  gpu:
    deviceId: "1"

zmq:
  image:
    repository: rtdt-zmq-service
    tag: latest
    pullPolicy: IfNotPresent
  environment:
    SERVICES_CNT: "1"
    ZMQ_PORT: "5555"
    NIM_TRITON_IP_ADDRESS: "localhost"
    NIM_TRITON_HTTP_PORT: "8080"
  resources:
    limits:
      stack: 67108864
      memlock: -1
  hostIPC: true

persistence:
  ovCache:
    storageClass: ""
    size: 3Gi
  ovLocalShare:
    storageClass: ""
    size: 3Gi 