[package]
# Semantic Versionning is used: https://semver.org/
version = "106.4.0-dev"

# Lists people or organizations that are considered the "authors" of the package.
authors = [
    "Max Rietmann <mrietmann@nvidia.com>",
]

# The title and description fields are primarily for displaying extension info in the UI
title = 'CGNS UI Explorer'
description = "CGNS file loader and explorer"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# Path (relative to the root) of changelog
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
# repository = "https://github.com/example/repository_name"

# One of categories for the UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example"]

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extension manager. It is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"ov.cgns" = {}

# Main python module this extension provides, it will be publicly available as "import ov.cgns_ui".
[[python.module]]
name = "ov.cgns_ui"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.test",
    "omni.kit.ui_test",  # UI testing extension
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
