{{- if and .Values.imagePullSecret.create .Values.imagePullSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  labels:
    {{- include "digital-twins-fluid-sim.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "digital-twins-fluid-sim.dockerconfigjson" . }}
{{- end }}
